export const ROUTES = {
  home: "/",
  shop: "/shop",
  productDetails: "/products/:id",
  login: "/auth/login",
  register: "/auth/register",
  wishlist: "wishlist",
  basket: "basket",
  checkout: "checkout",
  layout: "layout",
  ourStaff: "/dashboard/ourStaff",
  dashboardProducts: "/dashboard/products",
  productItem: "/dashboard/products/:id",
  category: "/dashboard/category",
} as const;
